export const GET_PRODUCTS_FOR_CUSTOMER = 'GET_PRODUCTS_FOR_CUSTOMER';
export const LOADING_GET_PRODUCTS_FOR_CUSTOMER =
  'LOADING_GET_PRODUCTS_FOR_CUSTOMER';

export const INC_OR_DEC_FROM_CART = 'INC_OR_DEC_FROM_CART';

export const LOADING_INC_OR_DEC_FROM_CART = 'LOADING_INC_OR_DEC_FROM_CART';
